// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `pushjob.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package segi.whcommon.push;

public interface _PushServiceIceOperationsNC
{
    resp.RpcRespIce push(MessageIce messageIce);

    resp.RpcRespIce pushList(java.util.List<MessageIce> list);

    resp.RpcRespIce delete(String businessKey, String msgTypeCode);
}
